### ISSUE TITLE
.env and .env.dev

### ISSUE THREAD

**Issue by zhik** [ANHD-NYC-CODE/anhd-council-client#139]
Hey @skut21x-ga, it seems the .env and .env.dev files are still exposed.

I will reset the s3 bucket keys on my end. But please reset the other keys that were exposed. 
Also hard remove the files on git 
[https://daily-dev-tips.com/posts/removing-a-env-file-from-git-history/](https://daily-dev-tips.com/posts/removing-a-env-file-from-git-history/)

**Comment by skut21x-ga** [comment]
Working on this ASAP.
